FROM golang:1.22.5-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o myaaw ./cmd/myaaw

FROM alpine:3.18
WORKDIR /app
COPY --from=builder /app/myaaw .

# Expose any ports if needed (if your consumer listens on a port)
# EXPOSE 8081

CMD ["./myaaw", "consumer", "run"]