FROM golang:1.22.5-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o myaaw ./cmd/myaaw

FROM alpine:3.18
WORKDIR /app
COPY --from=builder /app/myaaw .
COPY --from=builder /app/internal/tools/tools.json ./internal/tools/tools.json

EXPOSE 8080

CMD ["./myaaw", "server"]